/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MaterialId } from '../../src/types';

export interface MaterialProfile {
  id: MaterialId;
  canonicalName: string;
  category: 'ground' | 'liquid' | 'organic' | 'stone' | 'metal';
  surfaceStructure: string;
  colorPalette: string;
  smallScaleDetails: string;
  naturalVariation: string;
  descriptiveTerms: string[];
  visualCharacteristics: string[];
  positiveConstraints: string[];
  negativeConstraints: string[];
  tileWording: string[];
  forbiddenTerms: string[];
  providerGuidance?: string;
}

export const MATERIAL_PROFILES: Record<MaterialId, MaterialProfile> = {
  stone: {
    id: 'stone',
    canonicalName: 'Stone',
    category: 'stone',
    surfaceStructure: 'porous rock surface',
    colorPalette: 'slate and charcoal gray tones',
    smallScaleDetails: 'irregular small cracks and mineral pores',
    naturalVariation: 'natural mineral grain variation',
    descriptiveTerms: [
      'weathered dark stone',
      'rough porous rock surface',
      'irregular small cracks',
      'natural mineral patterns',
      'fine surface detail',
    ],
    visualCharacteristics: [
      'tactile stone relief',
      'mineral grain variation',
      'micro-cracks and pores',
    ],
    positiveConstraints: [
      'material surface',
      'seamless stone texture',
      'uniform rock coverage',
      'overhead stone surface',
    ],
    negativeConstraints: [
      'buildings',
      'houses',
      'roads',
      'characters',
      'sky',
      'horizon',
      'furniture',
      'lava',
      'water',
      'grass',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'building',
      'house',
      'vehicle',
      'car',
      'character',
      'person',
      'sky',
      'horizon',
      'window',
      'door',
      'roof',
      'lava',
      'water',
      'grass',
    ],
    providerGuidance: 'Focus strictly on uniform stone rock surface texture without structural objects.',
  },

  cobblestone: {
    id: 'cobblestone',
    canonicalName: 'Cobblestone',
    category: 'stone',
    surfaceStructure: 'interlocking paving blocks',
    colorPalette: 'weathered gray and charcoal tones',
    smallScaleDetails: 'tight mortar joints and chipped block edges',
    naturalVariation: 'natural mineral wear and block orientation variation',
    descriptiveTerms: [
      'ancient irregular cobblestones',
      'mortar joints',
      'chipped rock edges',
      'weathered pavement surface',
      'durable paving blocks',
    ],
    visualCharacteristics: [
      'tactile stone relief',
      'natural mineral wear',
      'tight mortar seams',
      'interlocking paving stones',
    ],
    positiveConstraints: [
      'pavement surface',
      'seamless stone texture',
      'uniform ground coverage',
      'stone paving',
    ],
    negativeConstraints: [
      'buildings',
      'houses',
      'roads with vehicles',
      'characters',
      'sky',
      'horizon',
      'furniture',
      'lava',
      'water',
      'grass',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'building',
      'house',
      'vehicle',
      'car',
      'character',
      'person',
      'sky',
      'horizon',
      'window',
      'door',
      'roof',
      'lava',
      'water',
      'grass',
    ],
    providerGuidance: 'Emphasize tight stone paving blocks and mortar lines from overhead view.',
  },

  brick: {
    id: 'brick',
    canonicalName: 'Brick',
    category: 'stone',
    surfaceStructure: 'repeating brick masonry blocks',
    colorPalette: 'terracotta red and gray mortar tones',
    smallScaleDetails: 'weathered brick edges and fine clay pores',
    naturalVariation: 'subtle brick shade variation',
    descriptiveTerms: [
      'weathered brick masonry',
      'individual brick blocks',
      'mortar joints',
      'rough clay texture',
      'aged brickwork surface',
    ],
    visualCharacteristics: [
      'repeating brick pattern',
      'tactile mortar lines',
      'weathered brick edges',
    ],
    positiveConstraints: [
      'brick surface',
      'seamless brick texture',
      'uniform masonry coverage',
      'brickwork',
    ],
    negativeConstraints: [
      'buildings',
      'houses',
      'doors',
      'windows',
      'characters',
      'sky',
      'horizon',
      'furniture',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'building',
      'house',
      'door',
      'window',
      'character',
      'person',
      'sky',
      'horizon',
      'roof',
    ],
    providerGuidance: 'Render flat brick surface masonry without building windows or doors.',
  },

  dirt: {
    id: 'dirt',
    canonicalName: 'Dirt',
    category: 'ground',
    surfaceStructure: 'compact soil surface',
    colorPalette: 'rich dark brown and umber tones',
    smallScaleDetails: 'fine earth particles and small embedded pebbles',
    naturalVariation: 'organic soil texture variation',
    descriptiveTerms: [
      'fine soil particles',
      'small pebbles',
      'subtle organic variation',
      'irregular granular structure',
      'compact earth surface',
    ],
    visualCharacteristics: [
      'granular soil texture',
      'embedded small pebbles',
      'earthy soil undertones',
    ],
    positiveConstraints: [
      'dirt ground surface',
      'seamless soil texture',
      'uniform dirt coverage',
      'flat terrain ground',
    ],
    negativeConstraints: [
      'buildings',
      'houses',
      'vehicles',
      'characters',
      'sky',
      'horizon',
      'furniture',
      'pavement',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'building',
      'house',
      'vehicle',
      'car',
      'character',
      'person',
      'sky',
      'horizon',
      'asphalt',
    ],
    providerGuidance: 'Direct view of fine soil earth surface with micro pebbles.',
  },

  sand: {
    id: 'sand',
    canonicalName: 'Sand',
    category: 'ground',
    surfaceStructure: 'smooth dune granule surface',
    colorPalette: 'golden sand and warm beige tones',
    smallScaleDetails: 'fine granules and micro ripple lines',
    naturalVariation: 'wind-swept ripple variation',
    descriptiveTerms: [
      'fine golden desert sand grains',
      'wind-blown micro-ripples',
      'smooth dune granule texture',
      'beach sand surface',
    ],
    visualCharacteristics: [
      'soft ripple lines',
      'fine granule texture',
      'even golden tone',
    ],
    positiveConstraints: [
      'sand ground surface',
      'seamless sand texture',
      'uniform sand coverage',
      'flat granular terrain',
    ],
    negativeConstraints: [
      'pyramids',
      'camels',
      'buildings',
      'vehicles',
      'characters',
      'sky',
      'horizon',
      'lava',
      'water',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'pyramid',
      'camel',
      'building',
      'house',
      'vehicle',
      'character',
      'person',
      'sky',
      'horizon',
      'lava',
      'water',
    ],
    providerGuidance: 'Direct view of smooth sand grain ground.',
  },

  wood: {
    id: 'wood',
    canonicalName: 'Wood',
    category: 'organic',
    surfaceStructure: 'parallel timber planks',
    colorPalette: 'warm oak and dark walnut tones',
    smallScaleDetails: 'subtle knots and fine wood grain',
    naturalVariation: 'organic grain variation',
    descriptiveTerms: [
      'weathered timber wood floor planks',
      'horizontal grain lines',
      'wood knots',
      'tactile lumber grooves',
      'hardwood surface',
    ],
    visualCharacteristics: [
      'natural wood grain',
      'soft lumber knots',
      'plank seams',
    ],
    positiveConstraints: [
      'wooden floor surface',
      'seamless wood texture',
      'uniform plank coverage',
      'timber flooring',
    ],
    negativeConstraints: [
      'furniture',
      'chairs',
      'tables',
      'houses',
      'buildings',
      'characters',
      'sky',
      'horizon',
      'lava',
      'water',
      'dirt',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'chair',
      'table',
      'furniture',
      'building',
      'house',
      'character',
      'person',
      'sky',
      'horizon',
      'lava',
      'water',
      'dirt',
    ],
    providerGuidance: 'Direct view of continuous wood planking.',
  },

  metal: {
    id: 'metal',
    canonicalName: 'Metal',
    category: 'metal',
    surfaceStructure: 'industrial sheet metal plate',
    colorPalette: 'steel gray and gunmetal tones',
    smallScaleDetails: 'fine brushed grain and micro scratches',
    naturalVariation: 'subtle metallic sheen variation',
    descriptiveTerms: [
      'brushed steel metal plate',
      'subtle micro scratches',
      'fine metallic surface grain',
      'industrial sheet metal',
      'realistic metal material',
    ],
    visualCharacteristics: [
      'brushed metallic sheen',
      'subtle surface scratches',
      'flat non-directional reflection',
    ],
    positiveConstraints: [
      'metal surface',
      'seamless metal texture',
      'uniform metal coverage',
      'metallic plate',
    ],
    negativeConstraints: [
      'robots',
      'machinery',
      'vehicles',
      'buildings',
      'characters',
      'sky',
      'horizon',
      'glare',
      'lens flare',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'robot',
      'machine',
      'vehicle',
      'car',
      'building',
      'character',
      'person',
      'sky',
      'horizon',
      'glare',
    ],
    providerGuidance: 'Render uniform brushed metal surface without specular glare or complex machinery.',
  },

  moss: {
    id: 'moss',
    canonicalName: 'Moss',
    category: 'organic',
    surfaceStructure: 'dense organic moss cushion',
    colorPalette: 'forest green and emerald moss tones',
    smallScaleDetails: 'small moss fronds and velvety tufts',
    naturalVariation: 'irregular organic growth patterns',
    descriptiveTerms: [
      'dense organic moss texture',
      'small moss structures',
      'irregular growth patterns',
      'subtle green variation',
      'soft velvety plant ground',
    ],
    visualCharacteristics: [
      'tactile moss cushions',
      'organic green tufts',
      'velvety surface depth',
    ],
    positiveConstraints: [
      'moss turf surface',
      'seamless moss texture',
      'uniform vegetation coverage',
      'organic growth',
    ],
    negativeConstraints: [
      'trees',
      'flowers',
      'houses',
      'buildings',
      'characters',
      'sky',
      'horizon',
      'animals',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'tree',
      'flower',
      'house',
      'building',
      'character',
      'person',
      'sky',
      'horizon',
      'animal',
    ],
    providerGuidance: 'Focus on dense organic moss growth filling the square surface uniformly.',
  },

  lava: {
    id: 'lava',
    canonicalName: 'Lava',
    category: 'liquid',
    surfaceStructure: 'molten magma channels with basalt rock crust',
    colorPalette: 'glowing orange-red fissures and dark charcoal crust',
    smallScaleDetails: 'emissive magma veins and micro embers',
    naturalVariation: 'fluid lava flow variation',
    descriptiveTerms: [
      'molten volcanic magma',
      'dark basalt rock crust',
      'glowing orange-red fissures',
      'liquid fire surface',
      'glowing lava veins',
    ],
    visualCharacteristics: [
      'emissive glowing cracks',
      'viscous fluid magma',
      'cooling dark basalt crust',
      'volcanic heat glow',
    ],
    positiveConstraints: [
      'material surface',
      'seamless ground texture',
      'uniform liquid magma coverage',
      'molten magma surface',
    ],
    negativeConstraints: [
      'buildings',
      'houses',
      'roads',
      'streets',
      'vehicles',
      'characters',
      'sky',
      'landscape',
      'architecture',
      'trees',
      'cobblestone',
      'water',
      'grass',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'building',
      'house',
      'road',
      'street',
      'vehicle',
      'car',
      'character',
      'person',
      'sky',
      'horizon',
      'tree',
      'cobblestone',
      'water',
      'grass',
      'window',
      'door',
      'roof',
      'arch',
      'castle',
    ],
    providerGuidance: 'Focus strictly on molten basalt lava ground texture surface without environment scene context.',
  },

  water: {
    id: 'water',
    canonicalName: 'Water',
    category: 'liquid',
    surfaceStructure: 'fluid water surface',
    colorPalette: 'turquoise aquatic blue and clear cyan tones',
    smallScaleDetails: 'shimmering caustic light patterns',
    naturalVariation: 'gentle surface ripple variation',
    descriptiveTerms: [
      'crystal-clear water surface',
      'caustic ripples',
      'transparent fluid depth',
      'turquoise aquatic surface',
      'gentle wavelets',
    ],
    visualCharacteristics: [
      'shimmering caustic light patterns',
      'fluid ripple lines',
      'subtle underwater depth',
    ],
    positiveConstraints: [
      'fluid surface',
      'seamless water texture',
      'uniform liquid coverage',
      'aquatic surface',
    ],
    negativeConstraints: [
      'boats',
      'ships',
      'buildings',
      'landscapes',
      'characters',
      'sky',
      'horizon',
      'islands',
      'lava',
      'cobblestone',
      'grass',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'boat',
      'ship',
      'building',
      'house',
      'character',
      'person',
      'sky',
      'horizon',
      'island',
      'tree',
      'lava',
      'cobblestone',
      'grass',
    ],
    providerGuidance: 'Render pure liquid surface ripples and caustics without land masses or vessels.',
  },

  grass: {
    id: 'grass',
    canonicalName: 'Grass',
    category: 'ground',
    surfaceStructure: 'dense meadow lawn turf',
    colorPalette: 'lush green meadow and earthy soil tones',
    smallScaleDetails: 'fine grass blade clusters and clovers',
    naturalVariation: 'soft blade direction variation',
    descriptiveTerms: [
      'lush green meadow grass turf',
      'fine blade clusters',
      'clovers',
      'earthy soil undertones',
      'natural lawn ground',
    ],
    visualCharacteristics: [
      'tactile grass blades',
      'soft natural green variation',
      'subtle soil patches',
    ],
    positiveConstraints: [
      'meadow ground surface',
      'seamless grass texture',
      'uniform lawn coverage',
      'vegetation turf',
    ],
    negativeConstraints: [
      'houses',
      'fences',
      'buildings',
      'vehicles',
      'characters',
      'sky',
      'horizon',
      'lava',
      'cobblestone',
      'water',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'house',
      'fence',
      'building',
      'vehicle',
      'character',
      'person',
      'sky',
      'horizon',
      'lava',
      'cobblestone',
      'water',
    ],
    providerGuidance: 'Focus on dense organic turf blades and natural ground cover without structures.',
  },
};

/**
 * Retrieves a material profile by canonical MaterialId or string, returning a strictly typed MaterialProfile
 */
export function getMaterialProfile(materialId: MaterialId | string): MaterialProfile {
  const norm = (materialId || 'stone').toLowerCase().trim();
  if (norm in MATERIAL_PROFILES) {
    return MATERIAL_PROFILES[norm as MaterialId];
  }

  // Fallback profile mapping custom unknown string inputs to a canonical MaterialProfile
  const capitalized = norm.charAt(0).toUpperCase() + norm.slice(1);
  return {
    id: 'stone', // Canonical fallback ID
    canonicalName: capitalized,
    category: 'ground',
    surfaceStructure: `${norm} surface structure`,
    colorPalette: `natural ${norm} color palette`,
    smallScaleDetails: `fine ${norm} surface detail`,
    naturalVariation: `natural ${norm} variation`,
    descriptiveTerms: [`${norm} material surface`, `natural ${norm} texture`],
    visualCharacteristics: [`tactile ${norm} details`],
    positiveConstraints: ['material surface', 'seamless ground texture', 'uniform coverage'],
    negativeConstraints: ['buildings', 'houses', 'roads', 'vehicles', 'characters', 'sky', 'horizon', 'landscape'],
    tileWording: ['seamless tileable texture', 'continuous pattern', 'no visible borders'],
    forbiddenTerms: ['building', 'house', 'road', 'vehicle', 'character', 'person', 'sky', 'horizon'],
  };
}
