/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MaterialId } from '../../src/types';

export interface MaterialProfile {
  id: MaterialId;
  canonicalName: string;
  category: 'ground' | 'liquid' | 'organic' | 'stone' | 'metal';
  surfaceStructure: string;
  colorPalette: string;
  smallScaleDetails: string;
  naturalVariation: string;
  descriptiveTerms: string[];
  visualCharacteristics: string[];
  positiveConstraints: string[];
  negativeConstraints: string[];
  tileWording: string[];
  forbiddenTerms: string[];
  providerGuidance?: string;
}

export const MATERIAL_PROFILES: Record<MaterialId, MaterialProfile> = {
  stone: {
    id: 'stone',
    canonicalName: 'Stone',
    category: 'stone',
    surfaceStructure: 'irregular rock structure, porous stone surface',
    colorPalette: 'subtle gray, slate, and charcoal color variation',
    smallScaleDetails: 'small cracks, fine pores, mineral particles',
    naturalVariation: 'rough granular surface, natural mineral patterns',
    descriptiveTerms: [
      'weathered dark stone',
      'rough porous rock surface',
      'irregular small cracks',
      'natural mineral patterns',
      'fine surface detail',
    ],
    visualCharacteristics: [
      'tactile stone relief',
      'mineral grain variation',
      'micro-cracks and pores',
    ],
    positiveConstraints: [
      'material surface',
      'seamless stone texture',
      'uniform rock coverage',
      'overhead stone surface',
    ],
    negativeConstraints: [
      'buildings',
      'houses',
      'roads',
      'characters',
      'sky',
      'horizon',
      'furniture',
      'lava',
      'water',
      'grass',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'building',
      'house',
      'vehicle',
      'car',
      'character',
      'person',
      'sky',
      'horizon',
      'window',
      'door',
      'roof',
      'lava',
      'water',
      'grass',
    ],
    providerGuidance: 'Focus strictly on uniform stone rock surface texture without structural objects.',
  },

  cobblestone: {
    id: 'cobblestone',
    canonicalName: 'Cobblestone',
    category: 'stone',
    surfaceStructure: 'irregular paving stone masonry structure, interlocking stone blocks',
    colorPalette: 'weathered gray, earth charcoal, and subtle mortar color variation',
    smallScaleDetails: 'tight mortar joints, chipped rock edges, micro-cracks',
    naturalVariation: 'natural stone mineral wear, random block orientation variation',
    descriptiveTerms: [
      'ancient irregular stone cobblestones',
      'mortar joints',
      'chipped rock edges',
      'weathered pavement surface',
      'durable stone blocks',
    ],
    visualCharacteristics: [
      'tactile stone relief',
      'natural mineral wear',
      'tight mortar seams',
      'interlocking paving stones',
    ],
    positiveConstraints: [
      'pavement surface',
      'seamless stone texture',
      'uniform ground coverage',
      'stone paving',
    ],
    negativeConstraints: [
      'buildings',
      'houses',
      'roads with vehicles',
      'characters',
      'sky',
      'horizon',
      'furniture',
      'lava',
      'water',
      'grass',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'building',
      'house',
      'vehicle',
      'car',
      'character',
      'person',
      'sky',
      'horizon',
      'window',
      'door',
      'roof',
      'lava',
      'water',
      'grass',
    ],
    providerGuidance: 'Emphasize tight stone paving blocks and mortar lines from overhead view.',
  },

  brick: {
    id: 'brick',
    canonicalName: 'Brick',
    category: 'stone',
    surfaceStructure: 'repeating masonry structure, individual brick surfaces',
    colorPalette: 'terracotta red, burnt orange, and gray mortar palette',
    smallScaleDetails: 'mortar variation, weathered edges, fine clay pores',
    naturalVariation: 'subtle color shade differences between bricks, natural weathering variation',
    descriptiveTerms: [
      'weathered brick masonry',
      'individual brick blocks',
      'mortar joints',
      'rough clay texture',
      'aged brickwork surface',
    ],
    visualCharacteristics: [
      'repeating brick pattern',
      'tactile mortar lines',
      'weathered brick edges',
    ],
    positiveConstraints: [
      'brick surface',
      'seamless brick texture',
      'uniform masonry coverage',
      'brickwork',
    ],
    negativeConstraints: [
      'buildings',
      'houses',
      'doors',
      'windows',
      'characters',
      'sky',
      'horizon',
      'furniture',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'building',
      'house',
      'door',
      'window',
      'character',
      'person',
      'sky',
      'horizon',
      'roof',
    ],
    providerGuidance: 'Render flat brick surface masonry without building windows or doors.',
  },

  dirt: {
    id: 'dirt',
    canonicalName: 'Dirt',
    category: 'ground',
    surfaceStructure: 'irregular granular structure, compact soil surface',
    colorPalette: 'rich dark brown, sienna, and umber soil tone variation',
    smallScaleDetails: 'fine soil particles, small pebble stones, organic specks',
    naturalVariation: 'subtle organic variation, natural soil grain distribution',
    descriptiveTerms: [
      'fine soil particles',
      'small stones',
      'subtle organic variation',
      'irregular granular structure',
      'compact earth surface',
    ],
    visualCharacteristics: [
      'granular soil texture',
      'embedded small pebbles',
      'earthy soil undertones',
    ],
    positiveConstraints: [
      'dirt ground surface',
      'seamless soil texture',
      'uniform dirt coverage',
      'flat terrain ground',
    ],
    negativeConstraints: [
      'buildings',
      'houses',
      'vehicles',
      'characters',
      'sky',
      'horizon',
      'furniture',
      'pavement',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'building',
      'house',
      'vehicle',
      'car',
      'character',
      'person',
      'sky',
      'horizon',
      'asphalt',
    ],
    providerGuidance: 'Direct view of fine soil earth surface with micro pebbles.',
  },

  sand: {
    id: 'sand',
    canonicalName: 'Sand',
    category: 'ground',
    surfaceStructure: 'smooth dune granule structure, fine sand grains',
    colorPalette: 'golden sand, warm beige, and subtle amber color variation',
    smallScaleDetails: 'fine grains, small shell fragments, micro ripple lines',
    naturalVariation: 'subtle wind-swept ripples, natural granular variation',
    descriptiveTerms: [
      'fine golden desert sand grains',
      'wind-blown micro-ripples',
      'smooth dune granule texture',
      'beach sand surface',
    ],
    visualCharacteristics: [
      'soft ripple lines',
      'fine granule texture',
      'even golden tone',
    ],
    positiveConstraints: [
      'sand ground surface',
      'seamless sand texture',
      'uniform sand coverage',
      'flat granular terrain',
    ],
    negativeConstraints: [
      'pyramids',
      'camels',
      'buildings',
      'vehicles',
      'characters',
      'sky',
      'horizon',
      'lava',
      'water',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'pyramid',
      'camel',
      'building',
      'house',
      'vehicle',
      'character',
      'person',
      'sky',
      'horizon',
      'lava',
      'water',
    ],
    providerGuidance: 'Direct view of smooth sand grain ground.',
  },

  wood: {
    id: 'wood',
    canonicalName: 'Wood',
    category: 'organic',
    surfaceStructure: 'continuous wood grain structure, parallel timber planking',
    colorPalette: 'warm oak, honey amber, and dark walnut tone variation',
    smallScaleDetails: 'subtle wood knots, fine lumber fibers, linear grain grooves',
    naturalVariation: 'irregular grain variation, subtle natural wood knots',
    descriptiveTerms: [
      'weathered timber wood floor planks',
      'horizontal grain lines',
      'wood knots',
      'tactile lumber grooves',
      'hardwood surface',
    ],
    visualCharacteristics: [
      'natural wood grain',
      'soft lumber knots',
      'plank seams',
    ],
    positiveConstraints: [
      'wooden floor surface',
      'seamless wood texture',
      'uniform plank coverage',
      'timber flooring',
    ],
    negativeConstraints: [
      'furniture',
      'chairs',
      'tables',
      'houses',
      'buildings',
      'characters',
      'sky',
      'horizon',
      'lava',
      'water',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'chair',
      'table',
      'furniture',
      'building',
      'house',
      'character',
      'person',
      'sky',
      'horizon',
      'lava',
      'water',
    ],
    providerGuidance: 'Direct view of continuous wood planking.',
  },

  metal: {
    id: 'metal',
    canonicalName: 'Metal',
    category: 'metal',
    surfaceStructure: 'fine brushed metallic surface, industrial metal plate',
    colorPalette: 'steel gray, gunmetal, and subtle silver highlight variation',
    smallScaleDetails: 'subtle micro scratches, fine brushed grain lines, tiny surface pitting',
    naturalVariation: 'realistic material variation, subtle oxidation and sheen changes',
    descriptiveTerms: [
      'brushed steel metal plate',
      'subtle micro scratches',
      'fine metallic surface grain',
      'industrial sheet metal',
      'realistic metal material',
    ],
    visualCharacteristics: [
      'brushed metallic sheen',
      'subtle surface scratches',
      'flat non-directional reflection',
    ],
    positiveConstraints: [
      'metal surface',
      'seamless metal texture',
      'uniform metal coverage',
      'metallic plate',
    ],
    negativeConstraints: [
      'robots',
      'machinery',
      'vehicles',
      'buildings',
      'characters',
      'sky',
      'horizon',
      'glare',
      'lens flare',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'robot',
      'machine',
      'vehicle',
      'car',
      'building',
      'character',
      'person',
      'sky',
      'horizon',
      'glare',
    ],
    providerGuidance: 'Render uniform brushed metal surface without specular glare or complex machinery.',
  },

  moss: {
    id: 'moss',
    canonicalName: 'Moss',
    category: 'organic',
    surfaceStructure: 'dense organic vegetation structure, soft velvety moss cushion',
    colorPalette: 'vibrant forest green, emerald, and dark moss olive variation',
    smallScaleDetails: 'small moss fronds, tiny organic clusters, microscopic leaf structures',
    naturalVariation: 'irregular organic growth patterns, subtle green shade variation',
    descriptiveTerms: [
      'dense organic moss texture',
      'small moss structures',
      'irregular growth patterns',
      'subtle green variation',
      'soft velvety plant ground',
    ],
    visualCharacteristics: [
      'tactile moss cushions',
      'organic green tufts',
      'velvety surface depth',
    ],
    positiveConstraints: [
      'moss turf surface',
      'seamless moss texture',
      'uniform vegetation coverage',
      'organic growth',
    ],
    negativeConstraints: [
      'trees',
      'flowers',
      'houses',
      'buildings',
      'characters',
      'sky',
      'horizon',
      'animals',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'tree',
      'flower',
      'house',
      'building',
      'character',
      'person',
      'sky',
      'horizon',
      'animal',
    ],
    providerGuidance: 'Focus on dense organic moss growth filling the square surface uniformly.',
  },

  lava: {
    id: 'lava',
    canonicalName: 'Lava',
    category: 'liquid',
    surfaceStructure: 'molten volcanic magma surface with cracked crust',
    colorPalette: 'glowing orange-red, fiery yellow fissures, and dark basalt charcoal crust',
    smallScaleDetails: 'emissive magma veins, cooling basalt flakes, micro glowing embers',
    naturalVariation: 'irregular lava fissure network, natural fluid magma variation',
    descriptiveTerms: [
      'molten volcanic magma',
      'dark basalt rock crust',
      'glowing orange-red fissures',
      'liquid fire surface',
      'glowing lava veins',
    ],
    visualCharacteristics: [
      'emissive glowing cracks',
      'viscous fluid magma',
      'cooling dark basalt crust',
      'volcanic heat glow',
    ],
    positiveConstraints: [
      'material surface',
      'seamless ground texture',
      'uniform liquid magma coverage',
      'molten magma surface',
    ],
    negativeConstraints: [
      'buildings',
      'houses',
      'roads',
      'streets',
      'vehicles',
      'characters',
      'sky',
      'landscape',
      'architecture',
      'trees',
      'cobblestone',
      'water',
      'grass',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'building',
      'house',
      'road',
      'street',
      'vehicle',
      'car',
      'character',
      'person',
      'sky',
      'horizon',
      'tree',
      'cobblestone',
      'water',
      'grass',
      'window',
      'door',
      'roof',
      'arch',
      'castle',
    ],
    providerGuidance: 'Focus strictly on molten basalt lava ground texture surface without environment scene context.',
  },

  water: {
    id: 'water',
    canonicalName: 'Water',
    category: 'liquid',
    surfaceStructure: 'fluid liquid surface structure, gentle surface ripples',
    colorPalette: 'turquoise aquatic blue, deep cyan, and clear crystal highlight palette',
    smallScaleDetails: 'shimmering caustic light patterns, micro wavelets, transparent depth',
    naturalVariation: 'natural caustic fluid variation, random surface wave patterns',
    descriptiveTerms: [
      'crystal-clear water surface',
      'caustic ripples',
      'transparent fluid depth',
      'turquoise aquatic surface',
      'gentle wavelets',
    ],
    visualCharacteristics: [
      'shimmering caustic light patterns',
      'fluid ripple lines',
      'subtle underwater depth',
    ],
    positiveConstraints: [
      'fluid surface',
      'seamless water texture',
      'uniform liquid coverage',
      'aquatic surface',
    ],
    negativeConstraints: [
      'boats',
      'ships',
      'buildings',
      'landscapes',
      'characters',
      'sky',
      'horizon',
      'islands',
      'lava',
      'cobblestone',
      'grass',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'boat',
      'ship',
      'building',
      'house',
      'character',
      'person',
      'sky',
      'horizon',
      'island',
      'tree',
      'lava',
      'cobblestone',
      'grass',
    ],
    providerGuidance: 'Render pure liquid surface ripples and caustics without land masses or vessels.',
  },

  grass: {
    id: 'grass',
    canonicalName: 'Grass',
    category: 'ground',
    surfaceStructure: 'dense blade cluster structure, natural lawn turf surface',
    colorPalette: 'lush meadow green, vibrant emerald, and earthy soil undertones',
    smallScaleDetails: 'fine blade clusters, small clover leaves, soil undertones',
    naturalVariation: 'random blade direction variation, soft natural color shade differences',
    descriptiveTerms: [
      'lush green meadow grass turf',
      'fine blade clusters',
      'clovers',
      'earthy soil undertones',
      'natural lawn ground',
    ],
    visualCharacteristics: [
      'tactile grass blades',
      'soft natural green variation',
      'subtle soil patches',
    ],
    positiveConstraints: [
      'meadow ground surface',
      'seamless grass texture',
      'uniform lawn coverage',
      'vegetation turf',
    ],
    negativeConstraints: [
      'houses',
      'fences',
      'buildings',
      'vehicles',
      'characters',
      'sky',
      'horizon',
      'lava',
      'cobblestone',
      'water',
    ],
    tileWording: [
      'seamless tileable texture',
      'continuous pattern',
      'no visible borders',
    ],
    forbiddenTerms: [
      'house',
      'fence',
      'building',
      'vehicle',
      'character',
      'person',
      'sky',
      'horizon',
      'lava',
      'cobblestone',
      'water',
    ],
    providerGuidance: 'Focus on dense organic turf blades and natural ground cover without structures.',
  },
};

/**
 * Retrieves a material profile by canonical MaterialId or string, returning a strictly typed MaterialProfile
 */
export function getMaterialProfile(materialId: MaterialId | string): MaterialProfile {
  const norm = (materialId || 'stone').toLowerCase().trim();
  if (norm in MATERIAL_PROFILES) {
    return MATERIAL_PROFILES[norm as MaterialId];
  }

  // Fallback profile mapping custom unknown string inputs to a canonical MaterialProfile
  const capitalized = norm.charAt(0).toUpperCase() + norm.slice(1);
  return {
    id: 'stone', // Canonical fallback ID
    canonicalName: capitalized,
    category: 'ground',
    surfaceStructure: `${norm} surface structure`,
    colorPalette: `natural ${norm} color palette`,
    smallScaleDetails: `fine ${norm} surface detail`,
    naturalVariation: `natural ${norm} variation`,
    descriptiveTerms: [`${norm} material surface`, `natural ${norm} texture`],
    visualCharacteristics: [`tactile ${norm} details`],
    positiveConstraints: ['material surface', 'seamless ground texture', 'uniform coverage'],
    negativeConstraints: ['buildings', 'houses', 'roads', 'vehicles', 'characters', 'sky', 'horizon', 'landscape'],
    tileWording: ['seamless tileable texture', 'continuous pattern', 'no visible borders'],
    forbiddenTerms: ['building', 'house', 'road', 'vehicle', 'character', 'person', 'sky', 'horizon'],
  };
}
